matrix:
  include:
    - language: csharp
      dist: trusty
      mono: none
      dotnet: 2.0.0
      install:
        - cd api/
        - dotnet restore
      script:
        - cd ../test/api/
        - dotnet build
        - dotnet test 
    - language: node_js
      node:
        - "9"
      install:
        - cd app/
        - yarn install
      script:
        - yarn test 