matrix:
  include:
    - language: csharp
      dist: trusty
      mono: none
      dotnet: 2.0.0
      install:
        - cd api/
        - dotnet restore
      script:
        - cd ../test/api/
        - dotnet build
        - dotnet test 
    - language: node_js
      dist: trusty
      node_js:
        - "9"
      install:
        - cd app/
        - yarn install
      script:
        - yarn test 
    - language: generic
      dist: trusty
      sudo: true
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t difftoolapi ./api
      - docker images
      - docker tag difftoolapi $DOCKER_USERNAME/difftoolapi
      - docker push $DOCKER_USERNAME/difftoolapi
      - docker build -t difftoolapp ./app
      - docker images
      - docker tag difftoolapp $DOCKER_USERNAME/difftoolapp
      - docker push $DOCKER_USERNAME/difftoolapp